// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Возвращает JWT токен по email и паролю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Войти в систему",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cars": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cars"
                ],
                "summary": "Список машин",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу (FREE, RENTED, REPAIR, SOLD)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по номеру (ILIKE)",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CarsListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cars"
                ],
                "summary": "Создать машину",
                "parameters": [
                    {
                        "description": "Данные машины",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCarRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Car"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cars/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cars"
                ],
                "summary": "Детали машины",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID машины",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CarDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cars"
                ],
                "summary": "Обновить машину",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID машины",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные машины",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Car"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cars"
                ],
                "summary": "Удалить машину",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID машины",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/contracts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Список договоров",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу (ACTIVE, COMPLETED, CANCELLED)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ContractsListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт договор, меняет статус машины на RENTED и генерирует платёжный график",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Создать договор",
                "parameters": [
                    {
                        "description": "Данные договора",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateContractRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Contract"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Машина не свободна",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/contracts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает договор с машиной, водителем и платежами. Пересчитывает paid_amount.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Детали договора",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ContractDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "При смене статуса с ACTIVE на другой — освобождает машину (FREE)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Обновить договор",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля для обновления",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ContractResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Удалить договор",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/contracts/{id}/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Платежи по договору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Payment"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает статистику по машинам, договорам, платежам, штрафам и топ должникам. Все запросы выполняются параллельно.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Сводная статистика",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DashboardResponse"
                        }
                    }
                }
            }
        },
        "/drivers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Список водителей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу (ACTIVE, INACTIVE)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по имени (ILIKE)",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DriversListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Создать водителя",
                "parameters": [
                    {
                        "description": "Данные водителя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateDriverRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Driver"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/drivers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Детали водителя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID водителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DriverDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Обновить водителя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID водителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные водителя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateDriverRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Driver"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Удалить водителя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID водителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fines": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fines"
                ],
                "summary": "Список штрафов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу (UNPAID, PAID, DISPUTED)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Фильтр по машине",
                        "name": "car_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Фильтр по водителю",
                        "name": "driver_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FinesListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Если driver_id не передан — определяется автоматически из активного договора машины",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fines"
                ],
                "summary": "Создать штраф",
                "parameters": [
                    {
                        "description": "Данные штрафа",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateFineRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Fine"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fines/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "При status=PAID проставляет paid_at. При status!=PAID сбрасывает paid_at в null.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fines"
                ],
                "summary": "Обновить штраф",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID штрафа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateFineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Fine"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fines"
                ],
                "summary": "Удалить штраф",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID штрафа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Проверяет доступность сервера и базы данных",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Без фильтра возвращает UNPAID + OVERDUE",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Список платежей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PAID, UNPAID, OVERDUE, PENDING (=UNPAID+OVERDUE)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaymentsListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отмечает платёж как PAID и пересчитывает paid_amount договора\nНельзя удалить оплаченный платёж",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "payments",
                    "payments"
                ],
                "summary": "Удалить платёж",
                "parameters": [
                    {
                        "description": "ID платежа и дата оплаты",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PayPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PayPaymentResponse"
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Платёж уже оплачен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/payments/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отмечает платёж как PAID и пересчитывает paid_amount договора\nНельзя удалить оплаченный платёж",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "payments",
                    "payments"
                ],
                "summary": "Удалить платёж",
                "parameters": [
                    {
                        "description": "ID платежа и дата оплаты",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PayPaymentRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID платежа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PayPaymentResponse"
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Платёж уже оплачен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Car": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inspection_before": {
                    "type": "string"
                },
                "mileage": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "osago_before": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.CarStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "vin": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "domain.CarStatus": {
            "type": "string",
            "enum": [
                "FREE",
                "RENTED",
                "REPAIR",
                "SOLD"
            ],
            "x-enum-varnames": [
                "CarStatusFree",
                "CarStatusRented",
                "CarStatusRepair",
                "CarStatusSold"
            ]
        },
        "domain.Contract": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "driver_id": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ContractStatus"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.ContractStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "COMPLETED",
                "CANCELLED"
            ],
            "x-enum-varnames": [
                "ContractStatusActive",
                "ContractStatusCompleted",
                "ContractStatusCancelled"
            ]
        },
        "domain.Driver": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "license_num": {
                    "type": "string"
                },
                "passport_num": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.DriverStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.DriverStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INACTIVE"
            ],
            "x-enum-varnames": [
                "DriverStatusActive",
                "DriverStatusInactive"
            ]
        },
        "domain.Fine": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "car_id": {
                    "type": "integer"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "driver_id": {
                    "type": "integer"
                },
                "fine_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.FineStatus"
                }
            }
        },
        "domain.FineStatus": {
            "type": "string",
            "enum": [
                "UNPAID",
                "PAID",
                "DISPUTED"
            ],
            "x-enum-varnames": [
                "FineStatusUnpaid",
                "FineStatusPaid",
                "FineStatusDisputed"
            ]
        },
        "domain.Payment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.PaymentStatus"
                }
            }
        },
        "domain.PaymentStatus": {
            "type": "string",
            "enum": [
                "PAID",
                "UNPAID",
                "OVERDUE"
            ],
            "x-enum-varnames": [
                "PaymentStatusPaid",
                "PaymentStatusUnpaid",
                "PaymentStatusOverdue"
            ]
        },
        "dto.ActiveContractBrief": {
            "type": "object",
            "properties": {
                "driver": {
                    "$ref": "#/definitions/dto.DriverName"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "dto.ActiveContractForDriver": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/dto.CarBrief"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.CarBrief": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                }
            }
        },
        "dto.CarDetailResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContractForCarDetail"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "fines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Fine"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "inspection_before": {
                    "type": "string"
                },
                "mileage": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "osago_before": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.CarStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "vin": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.CarForFine": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                }
            }
        },
        "dto.CarForPayment": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                }
            }
        },
        "dto.CarStats": {
            "type": "object",
            "properties": {
                "FREE": {
                    "type": "integer"
                },
                "RENTED": {
                    "type": "integer"
                },
                "REPAIR": {
                    "type": "integer"
                },
                "SOLD": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.CarWithContracts": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ActiveContractBrief"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inspection_before": {
                    "type": "string"
                },
                "mileage": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "osago_before": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.CarStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "vin": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.CarWithYear": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.CarsListResponse": {
            "type": "object",
            "properties": {
                "cars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CarWithContracts"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ContractDetailResponse": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/domain.Car"
                },
                "car_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "driver": {
                    "$ref": "#/definitions/domain.Driver"
                },
                "driver_id": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Payment"
                    }
                },
                "remaining_balance": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ContractStatus"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ContractForCarDetail": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "driver": {
                    "$ref": "#/definitions/domain.Driver"
                },
                "driver_id": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Payment"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ContractStatus"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ContractForFine": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.ContractForPayment": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/dto.CarForPayment"
                },
                "car_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "driver": {
                    "$ref": "#/definitions/dto.DriverForPayment"
                },
                "driver_id": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ContractListItem": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/dto.CarBrief"
                },
                "car_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "driver": {
                    "$ref": "#/definitions/dto.DriverName"
                },
                "driver_id": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "remaining_balance": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ContractStatus"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ContractResponse": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "driver_id": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "remaining_balance": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ContractStatus"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ContractStats": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                }
            }
        },
        "dto.ContractSummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "paid_amount": {
                    "type": "number"
                },
                "remaining_balance": {
                    "type": "number"
                }
            }
        },
        "dto.ContractWithCar": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/dto.CarWithYear"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "paid_amount": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ContractsListResponse": {
            "type": "object",
            "properties": {
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContractListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateCarRequest": {
            "type": "object",
            "required": [
                "brand",
                "model",
                "plate_number",
                "status",
                "vin",
                "year"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "inspection_before": {
                    "type": "string"
                },
                "mileage": {
                    "type": "integer",
                    "minimum": 0
                },
                "model": {
                    "type": "string"
                },
                "osago_before": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "FREE",
                        "RENTED",
                        "REPAIR",
                        "SOLD"
                    ]
                },
                "vin": {
                    "type": "string"
                },
                "year": {
                    "type": "integer",
                    "maximum": 2100,
                    "minimum": 1900
                }
            }
        },
        "dto.CreateContractRequest": {
            "type": "object",
            "required": [
                "car_id",
                "driver_id",
                "monthly_payment",
                "start_date",
                "total_amount"
            ],
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "driver_id": {
                    "type": "integer"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "dto.CreateDriverRequest": {
            "type": "object",
            "required": [
                "full_name",
                "license_num",
                "passport_num",
                "phone",
                "status"
            ],
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "license_num": {
                    "type": "string"
                },
                "passport_num": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "INACTIVE"
                    ]
                }
            }
        },
        "dto.CreateFineRequest": {
            "type": "object",
            "required": [
                "amount",
                "car_id",
                "description",
                "fine_date"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "car_id": {
                    "type": "integer"
                },
                "contract_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "driver_id": {
                    "type": "integer"
                },
                "fine_date": {
                    "type": "string"
                }
            }
        },
        "dto.DashboardResponse": {
            "type": "object",
            "properties": {
                "cars": {
                    "$ref": "#/definitions/dto.CarStats"
                },
                "contracts": {
                    "$ref": "#/definitions/dto.ContractStats"
                },
                "fines": {
                    "$ref": "#/definitions/dto.FineStats"
                },
                "payments": {
                    "$ref": "#/definitions/dto.PaymentStats"
                },
                "top_debtors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TopDebtor"
                    }
                }
            }
        },
        "dto.DriverDetailResponse": {
            "type": "object",
            "properties": {
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContractWithCar"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "license_num": {
                    "type": "string"
                },
                "passport_num": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.DriverStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.DriverForFine": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.DriverForPayment": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.DriverName": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                }
            }
        },
        "dto.DriverWithContracts": {
            "type": "object",
            "properties": {
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ActiveContractForDriver"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "license_num": {
                    "type": "string"
                },
                "passport_num": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.DriverStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.DriversListResponse": {
            "type": "object",
            "properties": {
                "drivers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DriverWithContracts"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.FineStats": {
            "type": "object",
            "properties": {
                "unpaid_amount": {
                    "type": "number"
                },
                "unpaid_count": {
                    "type": "integer"
                }
            }
        },
        "dto.FineWithRelations": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "car": {
                    "$ref": "#/definitions/dto.CarForFine"
                },
                "car_id": {
                    "type": "integer"
                },
                "contract": {
                    "$ref": "#/definitions/dto.ContractForFine"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "driver": {
                    "$ref": "#/definitions/dto.DriverForFine"
                },
                "driver_id": {
                    "type": "integer"
                },
                "fine_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.FineStatus"
                }
            }
        },
        "dto.FinesListResponse": {
            "type": "object",
            "properties": {
                "fines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FineWithRelations"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "dto.PayPaymentRequest": {
            "type": "object",
            "required": [
                "payment_id"
            ],
            "properties": {
                "paid_at": {
                    "type": "string"
                },
                "payment_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PayPaymentResponse": {
            "type": "object",
            "properties": {
                "contract": {
                    "$ref": "#/definitions/dto.ContractSummary"
                },
                "payment": {
                    "$ref": "#/definitions/domain.Payment"
                }
            }
        },
        "dto.PaymentStats": {
            "type": "object",
            "properties": {
                "collected_this_month": {
                    "type": "number"
                },
                "overdue_amount": {
                    "type": "number"
                },
                "overdue_count": {
                    "type": "integer"
                },
                "upcoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UpcomingPayment"
                    }
                }
            }
        },
        "dto.PaymentWithContract": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract": {
                    "$ref": "#/definitions/dto.ContractForPayment"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.PaymentStatus"
                }
            }
        },
        "dto.PaymentsListResponse": {
            "type": "object",
            "properties": {
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PaymentWithContract"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.TopDebtor": {
            "type": "object",
            "properties": {
                "car_label": {
                    "type": "string"
                },
                "car_plate": {
                    "type": "string"
                },
                "contract_id": {
                    "type": "integer"
                },
                "driver_id": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "max_days_overdue": {
                    "type": "integer"
                },
                "payment_count": {
                    "type": "integer"
                },
                "total_overdue": {
                    "type": "number"
                }
            }
        },
        "dto.UpcomingPayment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract": {
                    "$ref": "#/definitions/dto.UpcomingPaymentContract"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.PaymentStatus"
                }
            }
        },
        "dto.UpcomingPaymentCar": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "plate_number": {
                    "type": "string"
                }
            }
        },
        "dto.UpcomingPaymentContract": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/dto.UpcomingPaymentCar"
                },
                "driver": {
                    "$ref": "#/definitions/dto.UpcomingPaymentDriver"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpcomingPaymentDriver": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateCarRequest": {
            "type": "object",
            "required": [
                "brand",
                "model",
                "plate_number",
                "status",
                "vin",
                "year"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "inspection_before": {
                    "type": "string"
                },
                "mileage": {
                    "type": "integer",
                    "minimum": 0
                },
                "model": {
                    "type": "string"
                },
                "osago_before": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "FREE",
                        "RENTED",
                        "REPAIR",
                        "SOLD"
                    ]
                },
                "vin": {
                    "type": "string"
                },
                "year": {
                    "type": "integer",
                    "maximum": 2100,
                    "minimum": 1900
                }
            }
        },
        "dto.UpdateContractRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "COMPLETED",
                        "CANCELLED"
                    ]
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "dto.UpdateDriverRequest": {
            "type": "object",
            "required": [
                "full_name",
                "license_num",
                "passport_num",
                "phone",
                "status"
            ],
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "license_num": {
                    "type": "string"
                },
                "passport_num": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "INACTIVE"
                    ]
                }
            }
        },
        "dto.UpdateFineRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "UNPAID",
                        "PAID",
                        "DISPUTED"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Auto Hub API",
	Description:      "REST API для управления арендой автомобилей (CRM).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
